<?php

return [
    // Format: 'module' => ['OFFICE' => ['Name 1', 'Name 2']]
    'oil' => [
        'SUN' => [
            'Ramanda',
            'Agus Prawitno Sitohang',
            'Rizky Setiawan',
            'Andri Kaswari',
            'Dedi Prastiawan',
            'Ahmad Prawira Putra Pohan',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko',
            "KRISDIANTO WIBISONO ",
            "SURYA HANDANI K ",
            "IRWANDA ",
            "PRANS HARDIANSYAH SIMANJUNTAK ",
            "EKA ARDIANSYAH LUBIS ",
            "PANTAS JEKSON LIBERTO TAMPUBOLON ",
            "GANDA SUPRAPTO",
            "RUDI SAPUTRA"
        ],
        'YBS' => [
            'DONI SAPUTRA',
            'AFRIZA HELMI',
            'RIKI ABDULLAH',
            'RAHID',
            'REGI RINALDI',
            'RAHMADI',
            'ROPIANDI',
            'ERWINDO HASIHOLAN TAMBUNAN',
            'LEONARDO APRIAN PASKALIS SIHOTANG',
            'ARYA GAUTAMA S',
            'INDRA IRANA',
            'MUHAZZIR ALDIAN PANJAITAN',
            'HAIKAL DZIKRI DAMANIK',
            'RIZKI RAMADAN',
            'RISWANDI',
            'LAMA - FERI GUNAWAN',
            'DIMAS PRAYOGA',
            'SOETTA ELOKBUDI ARIN',
            'DENI SAPUTRA',
            'RINALDI',
            'RIKO SAPUTRA DONI',
            'ROMI AFRI YANDI',
            'ALDO PERNANDO',
            'ROMELDI',
            'NANDA SYAHPUTRA SILAEN',
            'MARDIANTO SAPUTRA',
            'APRIANDA TARIGAN',
            'YUDA PRANDIKA HASIBUAN',
            'MUHAMMAD SAFII',
            'AGUM SUNTORO',
            'WIRA CANDRA',
            'MUHAMMAD AL HAFIDZ',
            'MUHAMMAD IHSAN BAJA',
            'BOSMAN SIAHAAN',
            'YOGI SEPDUDEHIYA',
            'PEBRI SETIAWAN',
            'ONY HENDRAWAN',
            'ROBERTO BAGIO',
            'ROMI IRAWAN',
            'WILLIE ATHA RAHMAN',
            'SUPADI CHANDRA',
            'RAMA AGUNG',
            'RINGKI NAPOLA',
            'DENNY SAPITRA',
            'YOGA PANGESTU',
            'HERI SANJAYA',
            'FAUZI JOSHUA TAMPUBOLON',
            'ASRAL',
            'RIZKI REVO',
            'PANDHU BAHARI',
            'DANIEL SITOMPUL',
            'DWIKY ANDRIYAN',
            'IRFAN SHOLEH HARAHAP',
            'SUMADI INDRA ABADI',
            'FITRAH PRABOWO',
            'DALFI ASMANTO',
            'AKHIR ROMADHONA SIREGAR',
            'ARDHY FIRDAUS',
            'RISWAN',
            'ROBI APRIANTO',
            'GUSTIARA HASIBUAN',
            'AFRIZAL',
            'ARIF RAHMAN',
            'ARDIWINATA',
            'MELCHIANUS A.N',
            'MUSHAWWIR AWWAL',
            'BAMBANG NURDIANSYAH',
            'AJIZAN PRAYOGA',
            'CANDRA ANANDA',
            'FAHMI IDRIS',
            'WIRA PRATAMA',
            'FRANSLY SINAMBELA',
            'JANUAR RAMHADAN',
            'RAHMAT AIDIL PUTRA',
            'RAHMAT HIDAYAT',
            'M. RIDWAN',
            'ANDIKA PRATAMA',
            'RIAN IDRIS',
            'ALDI DARMA',
            'ARDI GHAFRANAKA',
            'ARBYE DANIEL SIBURIAN',
            'OLOAN SAHAT MARUBA SIMANJUNTAK',
            'ROYMON EFENDI',
            'FIKRI HIDAYAT',
            'EDON PUTRA',
            'EKI PUTRA',
            'SUGENG MAULANA',
            'TAUFIQ HIDAYAT',
            'HARI ANDRO ROBI MAHYU',
            'ARIF FIDDIN',
            'AZWIN SYAHPUTRA',
            'USMAN NASRULLAH',
            'TINO ANDRIANO',
            'AHMAD SAIMUN',
            'ISWANDI',
            'HARIZON',
            'JEFRI SAAT PRANATA TAMBA',
            'WANTA ASTRIA',
            'AHMAD DUKI',
            'M. FAJAR ERIN',
            'RAMBI PATTIALA',
            'DEDI SUHENDRI SINAGA',
            'CACA HANDIKA',
            'DHARMA PUTRA PRATAMA',
            'JEVINA LIVIANI',
            'ULI YULIANA',
            'WANDA SYAHPUTRA SIREGAR',
            'WAHYU',
            'ARIF RIDHO',
            'NURHADI',
            'MUHAMMAD ADI SURYA',
            'GUSTI RIYANDI',
            'ALVIANDI SAPUTRA',
            'SUPRIADI',
            'REFLY YANTO',
            'HENKI CANDRA',
            'AYUP PAHRI BUTAR-BUTAR',
            'ELIEZER YOSUA',
            'RIDWAN',
            'FRANSISKUS TIKKOS P SITUMORANG',
            'SOPAN SOFIAN SITANGGANG',
            'ALI SAHRUL MULIADI HASIBUAN',
            'IRVAN ROYNALDY',
            'DWIKA RAJA SYAHPUTRA PURBA',
            'HALIMAH TUSADDIAH DAULAY',
            'KHAIRUL FAHMI',
            'SISWANDO',
            'REFANDO MALAU',
            'RIAN GIBEL SIAHAAN',
            'RULI AKBAR',
            'ARIS MARJOHAN',
            'SALOMO SITUMORANG',
            'TOMI PUTRA SIMARE MARE',
            'MUHAMMAD IKMAL',
            'PATRISIUS CHARLOS SITUMORANG',
            'POLMAN PAULUS SIDABUTAR',
            'JUPRIADI',
            'SETIA ARDINTA',
            'ZULFAHMI',
            'SAS FEGO RIKANDOKA',
            'SYAHRUL EFENDI',
            'VIVI FEBIANTY',
            'YOGI DWI SAPUTRA',
            'RIZKI ARDIAN SINAGA',
            'GABE HAMORAON',
            'HAKIM LUMBANTORUAN',
            'YOGA RYADINATA',
            'WANTO',
            'YOGIE SAPUTRA',
            'TAHI SIANTURI',
            'AFIK VIO PRATAMA',
            'WEWEN SAPUTRA',
            'WIKKI SAMUEL SILITONGA',
            'ALFAJRI',
            'AGUNG ANANDHA'
        ],
        'SJN' => [],
    ],
    'kernel' => [
        'YBS' => [
            'DONI SAPUTRA',
            'AFRIZA HELMI',
            'RIKI ABDULLAH',
            'RAHID',
            'REGI RINALDI',
            'RAHMADI',
            'ROPIANDI',
            'ERWINDO HASIHOLAN TAMBUNAN',
            'LEONARDO APRIAN PASKALIS SIHOTANG',
            'ARYA GAUTAMA S',
            'INDRA IRANA',
            'MUHAZZIR ALDIAN PANJAITAN',
            'HAIKAL DZIKRI DAMANIK',
            'RIZKI RAMADAN',
            'RISWANDI',
            'LAMA - FERI GUNAWAN',
            'DIMAS PRAYOGA',
            'SOETTA ELOKBUDI ARIN',
            'DENI SAPUTRA',
            'RINALDI',
            'RIKO SAPUTRA DONI',
            'ROMI AFRI YANDI',
            'ALDO PERNANDO',
            'ROMELDI',
            'NANDA SYAHPUTRA SILAEN',
            'MARDIANTO SAPUTRA',
            'APRIANDA TARIGAN',
            'YUDA PRANDIKA HASIBUAN',
            'MUHAMMAD SAFII',
            'AGUM SUNTORO',
            'WIRA CANDRA',
            'MUHAMMAD AL HAFIDZ',
            'MUHAMMAD IHSAN BAJA',
            'BOSMAN SIAHAAN',
            'YOGI SEPDUDEHIYA',
            'PEBRI SETIAWAN',
            'ONY HENDRAWAN',
            'ROBERTO BAGIO',
            'ROMI IRAWAN',
            'WILLIE ATHA RAHMAN',
            'SUPADI CHANDRA',
            'RAMA AGUNG',
            'RINGKI NAPOLA',
            'DENNY SAPITRA',
            'YOGA PANGESTU',
            'HERI SANJAYA',
            'FAUZI JOSHUA TAMPUBOLON',
            'ASRAL',
            'RIZKI REVO',
            'PANDHU BAHARI',
            'DANIEL SITOMPUL',
            'DWIKY ANDRIYAN',
            'IRFAN SHOLEH HARAHAP',
            'SUMADI INDRA ABADI',
            'FITRAH PRABOWO',
            'DALFI ASMANTO',
            'AKHIR ROMADHONA SIREGAR',
            'ARDHY FIRDAUS',
            'RISWAN',
            'ROBI APRIANTO',
            'GUSTIARA HASIBUAN',
            'AFRIZAL',
            'ARIF RAHMAN',
            'ARDIWINATA',
            'MELCHIANUS A.N',
            'MUSHAWWIR AWWAL',
            'BAMBANG NURDIANSYAH',
            'AJIZAN PRAYOGA',
            'CANDRA ANANDA',
            'FAHMI IDRIS',
            'WIRA PRATAMA',
            'FRANSLY SINAMBELA',
            'JANUAR RAMHADAN',
            'RAHMAT AIDIL PUTRA',
            'RAHMAT HIDAYAT',
            'M. RIDWAN',
            'ANDIKA PRATAMA',
            'RIAN IDRIS',
            'ALDI DARMA',
            'ARDI GHAFRANAKA',
            'ARBYE DANIEL SIBURIAN',
            'OLOAN SAHAT MARUBA SIMANJUNTAK',
            'ROYMON EFENDI',
            'FIKRI HIDAYAT',
            'EDON PUTRA',
            'EKI PUTRA',
            'SUGENG MAULANA',
            'TAUFIQ HIDAYAT',
            'HARI ANDRO ROBI MAHYU',
            'ARIF FIDDIN',
            'AZWIN SYAHPUTRA',
            'USMAN NASRULLAH',
            'TINO ANDRIANO',
            'AHMAD SAIMUN',
            'ISWANDI',
            'HARIZON',
            'JEFRI SAAT PRANATA TAMBA',
            'WANTA ASTRIA',
            'AHMAD DUKI',
            'M. FAJAR ERIN',
            'RAMBI PATTIALA',
            'DEDI SUHENDRI SINAGA',
            'CACA HANDIKA',
            'DHARMA PUTRA PRATAMA',
            'JEVINA LIVIANI',
            'ULI YULIANA',
            'WANDA SYAHPUTRA SIREGAR',
            'WAHYU',
            'ARIF RIDHO',
            'NURHADI',
            'MUHAMMAD ADI SURYA',
            'GUSTI RIYANDI',
            'ALVIANDI SAPUTRA',
            'SUPRIADI',
            'REFLY YANTO',
            'HENKI CANDRA',
            'AYUP PAHRI BUTAR-BUTAR',
            'ELIEZER YOSUA',
            'RIDWAN',
            'FRANSISKUS TIKKOS P SITUMORANG',
            'SOPAN SOFIAN SITANGGANG',
            'ALI SAHRUL MULIADI HASIBUAN',
            'IRVAN ROYNALDY',
            'DWIKA RAJA SYAHPUTRA PURBA',
            'HALIMAH TUSADDIAH DAULAY',
            'KHAIRUL FAHMI',
            'SISWANDO',
            'REFANDO MALAU',
            'RIAN GIBEL SIAHAAN',
            'RULI AKBAR',
            'ARIS MARJOHAN',
            'SALOMO SITUMORANG',
            'TOMI PUTRA SIMARE MARE',
            'MUHAMMAD IKMAL',
            'PATRISIUS CHARLOS SITUMORANG',
            'POLMAN PAULUS SIDABUTAR',
            'JUPRIADI',
            'SETIA ARDINTA',
            'ZULFAHMI',
            'SAS FEGO RIKANDOKA',
            'SYAHRUL EFENDI',
            'VIVI FEBIANTY',
            'YOGI DWI SAPUTRA',
            'RIZKI ARDIAN SINAGA',
            'GABE HAMORAON',
            'HAKIM LUMBANTORUAN',
            'YOGA RYADINATA',
            'WANTO',
            'YOGIE SAPUTRA',
            'TAHI SIANTURI',
            'AFIK VIO PRATAMA',
            'WEWEN SAPUTRA',
            'WIKKI SAMUEL SILITONGA',
            'ALFAJRI',
            'AGUNG ANANDHA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko',
            "KRISDIANTO WIBISONO ",
            "SURYA HANDANI K ",
            "IRWANDA ",
            "PRANS HARDIANSYAH SIMANJUNTAK ",
            "EKA ARDIANSYAH LUBIS ",
            "PANTAS JEKSON LIBERTO TAMPUBOLON ",
        ],
        'SJN' => [],
    ],
    'dirt_moist' => [
        'YBS' => [
            'DONI SAPUTRA',
            'AFRIZA HELMI',
            'RIKI ABDULLAH',
            'RAHID',
            'REGI RINALDI',
            'RAHMADI',
            'ROPIANDI',
            'ERWINDO HASIHOLAN TAMBUNAN',
            'LEONARDO APRIAN PASKALIS SIHOTANG',
            'ARYA GAUTAMA S',
            'INDRA IRANA',
            'MUHAZZIR ALDIAN PANJAITAN',
            'HAIKAL DZIKRI DAMANIK',
            'RIZKI RAMADAN',
            'RISWANDI',
            'LAMA - FERI GUNAWAN',
            'DIMAS PRAYOGA',
            'SOETTA ELOKBUDI ARIN',
            'DENI SAPUTRA',
            'RINALDI',
            'RIKO SAPUTRA DONI',
            'ROMI AFRI YANDI',
            'ALDO PERNANDO',
            'ROMELDI',
            'NANDA SYAHPUTRA SILAEN',
            'MARDIANTO SAPUTRA',
            'APRIANDA TARIGAN',
            'YUDA PRANDIKA HASIBUAN',
            'MUHAMMAD SAFII',
            'AGUM SUNTORO',
            'WIRA CANDRA',
            'MUHAMMAD AL HAFIDZ',
            'MUHAMMAD IHSAN BAJA',
            'BOSMAN SIAHAAN',
            'YOGI SEPDUDEHIYA',
            'PEBRI SETIAWAN',
            'ONY HENDRAWAN',
            'ROBERTO BAGIO',
            'ROMI IRAWAN',
            'WILLIE ATHA RAHMAN',
            'SUPADI CHANDRA',
            'RAMA AGUNG',
            'RINGKI NAPOLA',
            'DENNY SAPITRA',
            'YOGA PANGESTU',
            'HERI SANJAYA',
            'FAUZI JOSHUA TAMPUBOLON',
            'ASRAL',
            'RIZKI REVO',
            'PANDHU BAHARI',
            'DANIEL SITOMPUL',
            'DWIKY ANDRIYAN',
            'IRFAN SHOLEH HARAHAP',
            'SUMADI INDRA ABADI',
            'FITRAH PRABOWO',
            'DALFI ASMANTO',
            'AKHIR ROMADHONA SIREGAR',
            'ARDHY FIRDAUS',
            'RISWAN',
            'ROBI APRIANTO',
            'GUSTIARA HASIBUAN',
            'AFRIZAL',
            'ARIF RAHMAN',
            'ARDIWINATA',
            'MELCHIANUS A.N',
            'MUSHAWWIR AWWAL',
            'BAMBANG NURDIANSYAH',
            'AJIZAN PRAYOGA',
            'CANDRA ANANDA',
            'FAHMI IDRIS',
            'WIRA PRATAMA',
            'FRANSLY SINAMBELA',
            'JANUAR RAMHADAN',
            'RAHMAT AIDIL PUTRA',
            'RAHMAT HIDAYAT',
            'M. RIDWAN',
            'ANDIKA PRATAMA',
            'RIAN IDRIS',
            'ALDI DARMA',
            'ARDI GHAFRANAKA',
            'ARBYE DANIEL SIBURIAN',
            'OLOAN SAHAT MARUBA SIMANJUNTAK',
            'ROYMON EFENDI',
            'FIKRI HIDAYAT',
            'EDON PUTRA',
            'EKI PUTRA',
            'SUGENG MAULANA',
            'TAUFIQ HIDAYAT',
            'HARI ANDRO ROBI MAHYU',
            'ARIF FIDDIN',
            'AZWIN SYAHPUTRA',
            'USMAN NASRULLAH',
            'TINO ANDRIANO',
            'AHMAD SAIMUN',
            'ISWANDI',
            'HARIZON',
            'JEFRI SAAT PRANATA TAMBA',
            'WANTA ASTRIA',
            'AHMAD DUKI',
            'M. FAJAR ERIN',
            'RAMBI PATTIALA',
            'DEDI SUHENDRI SINAGA',
            'CACA HANDIKA',
            'DHARMA PUTRA PRATAMA',
            'JEVINA LIVIANI',
            'ULI YULIANA',
            'WANDA SYAHPUTRA SIREGAR',
            'WAHYU',
            'ARIF RIDHO',
            'NURHADI',
            'MUHAMMAD ADI SURYA',
            'GUSTI RIYANDI',
            'ALVIANDI SAPUTRA',
            'SUPRIADI',
            'REFLY YANTO',
            'HENKI CANDRA',
            'AYUP PAHRI BUTAR-BUTAR',
            'ELIEZER YOSUA',
            'RIDWAN',
            'FRANSISKUS TIKKOS P SITUMORANG',
            'SOPAN SOFIAN SITANGGANG',
            'ALI SAHRUL MULIADI HASIBUAN',
            'IRVAN ROYNALDY',
            'DWIKA RAJA SYAHPUTRA PURBA',
            'HALIMAH TUSADDIAH DAULAY',
            'KHAIRUL FAHMI',
            'SISWANDO',
            'REFANDO MALAU',
            'RIAN GIBEL SIAHAAN',
            'RULI AKBAR',
            'ARIS MARJOHAN',
            'SALOMO SITUMORANG',
            'TOMI PUTRA SIMARE MARE',
            'MUHAMMAD IKMAL',
            'PATRISIUS CHARLOS SITUMORANG',
            'POLMAN PAULUS SIDABUTAR',
            'JUPRIADI',
            'SETIA ARDINTA',
            'ZULFAHMI',
            'SAS FEGO RIKANDOKA',
            'SYAHRUL EFENDI',
            'VIVI FEBIANTY',
            'YOGI DWI SAPUTRA',
            'RIZKI ARDIAN SINAGA',
            'GABE HAMORAON',
            'HAKIM LUMBANTORUAN',
            'YOGA RYADINATA',
            'WANTO',
            'YOGIE SAPUTRA',
            'TAHI SIANTURI',
            'AFIK VIO PRATAMA',
            'WEWEN SAPUTRA',
            'WIKKI SAMUEL SILITONGA',
            'ALFAJRI',
            'AGUNG ANANDHA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko',
            "KRISDIANTO WIBISONO ",
            "SURYA HANDANI K ",
            "IRWANDA ",
            "PRANS HARDIANSYAH SIMANJUNTAK ",
            "EKA ARDIANSYAH LUBIS ",
            "PANTAS JEKSON LIBERTO TAMPUBOLON ",
        ],
        'SJN' => [],
    ],
    'qwt' => [
        'YBS' => [
            'DONI SAPUTRA',
            'AFRIZA HELMI',
            'RIKI ABDULLAH',
            'RAHID',
            'REGI RINALDI',
            'RAHMADI',
            'ROPIANDI',
            'ERWINDO HASIHOLAN TAMBUNAN',
            'LEONARDO APRIAN PASKALIS SIHOTANG',
            'ARYA GAUTAMA S',
            'INDRA IRANA',
            'MUHAZZIR ALDIAN PANJAITAN',
            'HAIKAL DZIKRI DAMANIK',
            'RIZKI RAMADAN',
            'RISWANDI',
            'LAMA - FERI GUNAWAN',
            'DIMAS PRAYOGA',
            'SOETTA ELOKBUDI ARIN',
            'DENI SAPUTRA',
            'RINALDI',
            'RIKO SAPUTRA DONI',
            'ROMI AFRI YANDI',
            'ALDO PERNANDO',
            'ROMELDI',
            'NANDA SYAHPUTRA SILAEN',
            'MARDIANTO SAPUTRA',
            'APRIANDA TARIGAN',
            'YUDA PRANDIKA HASIBUAN',
            'MUHAMMAD SAFII',
            'AGUM SUNTORO',
            'WIRA CANDRA',
            'MUHAMMAD AL HAFIDZ',
            'MUHAMMAD IHSAN BAJA',
            'BOSMAN SIAHAAN',
            'YOGI SEPDUDEHIYA',
            'PEBRI SETIAWAN',
            'ONY HENDRAWAN',
            'ROBERTO BAGIO',
            'ROMI IRAWAN',
            'WILLIE ATHA RAHMAN',
            'SUPADI CHANDRA',
            'RAMA AGUNG',
            'RINGKI NAPOLA',
            'DENNY SAPITRA',
            'YOGA PANGESTU',
            'HERI SANJAYA',
            'FAUZI JOSHUA TAMPUBOLON',
            'ASRAL',
            'RIZKI REVO',
            'PANDHU BAHARI',
            'DANIEL SITOMPUL',
            'DWIKY ANDRIYAN',
            'IRFAN SHOLEH HARAHAP',
            'SUMADI INDRA ABADI',
            'FITRAH PRABOWO',
            'DALFI ASMANTO',
            'AKHIR ROMADHONA SIREGAR',
            'ARDHY FIRDAUS',
            'RISWAN',
            'ROBI APRIANTO',
            'GUSTIARA HASIBUAN',
            'AFRIZAL',
            'ARIF RAHMAN',
            'ARDIWINATA',
            'MELCHIANUS A.N',
            'MUSHAWWIR AWWAL',
            'BAMBANG NURDIANSYAH',
            'AJIZAN PRAYOGA',
            'CANDRA ANANDA',
            'FAHMI IDRIS',
            'WIRA PRATAMA',
            'FRANSLY SINAMBELA',
            'JANUAR RAMHADAN',
            'RAHMAT AIDIL PUTRA',
            'RAHMAT HIDAYAT',
            'M. RIDWAN',
            'ANDIKA PRATAMA',
            'RIAN IDRIS',
            'ALDI DARMA',
            'ARDI GHAFRANAKA',
            'ARBYE DANIEL SIBURIAN',
            'OLOAN SAHAT MARUBA SIMANJUNTAK',
            'ROYMON EFENDI',
            'FIKRI HIDAYAT',
            'EDON PUTRA',
            'EKI PUTRA',
            'SUGENG MAULANA',
            'TAUFIQ HIDAYAT',
            'HARI ANDRO ROBI MAHYU',
            'ARIF FIDDIN',
            'AZWIN SYAHPUTRA',
            'USMAN NASRULLAH',
            'TINO ANDRIANO',
            'AHMAD SAIMUN',
            'ISWANDI',
            'HARIZON',
            'JEFRI SAAT PRANATA TAMBA',
            'WANTA ASTRIA',
            'AHMAD DUKI',
            'M. FAJAR ERIN',
            'RAMBI PATTIALA',
            'DEDI SUHENDRI SINAGA',
            'CACA HANDIKA',
            'DHARMA PUTRA PRATAMA',
            'JEVINA LIVIANI',
            'ULI YULIANA',
            'WANDA SYAHPUTRA SIREGAR',
            'WAHYU',
            'ARIF RIDHO',
            'NURHADI',
            'MUHAMMAD ADI SURYA',
            'GUSTI RIYANDI',
            'ALVIANDI SAPUTRA',
            'SUPRIADI',
            'REFLY YANTO',
            'HENKI CANDRA',
            'AYUP PAHRI BUTAR-BUTAR',
            'ELIEZER YOSUA',
            'RIDWAN',
            'FRANSISKUS TIKKOS P SITUMORANG',
            'SOPAN SOFIAN SITANGGANG',
            'ALI SAHRUL MULIADI HASIBUAN',
            'IRVAN ROYNALDY',
            'DWIKA RAJA SYAHPUTRA PURBA',
            'HALIMAH TUSADDIAH DAULAY',
            'KHAIRUL FAHMI',
            'SISWANDO',
            'REFANDO MALAU',
            'RIAN GIBEL SIAHAAN',
            'RULI AKBAR',
            'ARIS MARJOHAN',
            'SALOMO SITUMORANG',
            'TOMI PUTRA SIMARE MARE',
            'MUHAMMAD IKMAL',
            'PATRISIUS CHARLOS SITUMORANG',
            'POLMAN PAULUS SIDABUTAR',
            'JUPRIADI',
            'SETIA ARDINTA',
            'ZULFAHMI',
            'SAS FEGO RIKANDOKA',
            'SYAHRUL EFENDI',
            'VIVI FEBIANTY',
            'YOGI DWI SAPUTRA',
            'RIZKI ARDIAN SINAGA',
            'GABE HAMORAON',
            'HAKIM LUMBANTORUAN',
            'YOGA RYADINATA',
            'WANTO',
            'YOGIE SAPUTRA',
            'TAHI SIANTURI',
            'AFIK VIO PRATAMA',
            'WEWEN SAPUTRA',
            'WIKKI SAMUEL SILITONGA',
            'ALFAJRI',
            'AGUNG ANANDHA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko',
            "KRISDIANTO WIBISONO ",
            "SURYA HANDANI K ",
            "IRWANDA ",
            "PRANS HARDIANSYAH SIMANJUNTAK ",
            "EKA ARDIANSYAH LUBIS ",
            "PANTAS JEKSON LIBERTO TAMPUBOLON ",
            "ARIFANDI BAYU"
        ],
        'SJN' => [],
    ],
    'ripple_mill' => [
        'YBS' => [
            'DONI SAPUTRA',
            'AFRIZA HELMI',
            'RIKI ABDULLAH',
            'RAHID',
            'REGI RINALDI',
            'RAHMADI',
            'ROPIANDI',
            'ERWINDO HASIHOLAN TAMBUNAN',
            'LEONARDO APRIAN PASKALIS SIHOTANG',
            'ARYA GAUTAMA S',
            'INDRA IRANA',
            'MUHAZZIR ALDIAN PANJAITAN',
            'HAIKAL DZIKRI DAMANIK',
            'RIZKI RAMADAN',
            'RISWANDI',
            'LAMA - FERI GUNAWAN',
            'DIMAS PRAYOGA',
            'SOETTA ELOKBUDI ARIN',
            'DENI SAPUTRA',
            'RINALDI',
            'RIKO SAPUTRA DONI',
            'ROMI AFRI YANDI',
            'ALDO PERNANDO',
            'ROMELDI',
            'NANDA SYAHPUTRA SILAEN',
            'MARDIANTO SAPUTRA',
            'APRIANDA TARIGAN',
            'YUDA PRANDIKA HASIBUAN',
            'MUHAMMAD SAFII',
            'AGUM SUNTORO',
            'WIRA CANDRA',
            'MUHAMMAD AL HAFIDZ',
            'MUHAMMAD IHSAN BAJA',
            'BOSMAN SIAHAAN',
            'YOGI SEPDUDEHIYA',
            'PEBRI SETIAWAN',
            'ONY HENDRAWAN',
            'ROBERTO BAGIO',
            'ROMI IRAWAN',
            'WILLIE ATHA RAHMAN',
            'SUPADI CHANDRA',
            'RAMA AGUNG',
            'RINGKI NAPOLA',
            'DENNY SAPITRA',
            'YOGA PANGESTU',
            'HERI SANJAYA',
            'FAUZI JOSHUA TAMPUBOLON',
            'ASRAL',
            'RIZKI REVO',
            'PANDHU BAHARI',
            'DANIEL SITOMPUL',
            'DWIKY ANDRIYAN',
            'IRFAN SHOLEH HARAHAP',
            'SUMADI INDRA ABADI',
            'FITRAH PRABOWO',
            'DALFI ASMANTO',
            'AKHIR ROMADHONA SIREGAR',
            'ARDHY FIRDAUS',
            'RISWAN',
            'ROBI APRIANTO',
            'GUSTIARA HASIBUAN',
            'AFRIZAL',
            'ARIF RAHMAN',
            'ARDIWINATA',
            'MELCHIANUS A.N',
            'MUSHAWWIR AWWAL',
            'BAMBANG NURDIANSYAH',
            'AJIZAN PRAYOGA',
            'CANDRA ANANDA',
            'FAHMI IDRIS',
            'WIRA PRATAMA',
            'FRANSLY SINAMBELA',
            'JANUAR RAMHADAN',
            'RAHMAT AIDIL PUTRA',
            'RAHMAT HIDAYAT',
            'M. RIDWAN',
            'ANDIKA PRATAMA',
            'RIAN IDRIS',
            'ALDI DARMA',
            'ARDI GHAFRANAKA',
            'ARBYE DANIEL SIBURIAN',
            'OLOAN SAHAT MARUBA SIMANJUNTAK',
            'ROYMON EFENDI',
            'FIKRI HIDAYAT',
            'EDON PUTRA',
            'EKI PUTRA',
            'SUGENG MAULANA',
            'TAUFIQ HIDAYAT',
            'HARI ANDRO ROBI MAHYU',
            'ARIF FIDDIN',
            'AZWIN SYAHPUTRA',
            'USMAN NASRULLAH',
            'TINO ANDRIANO',
            'AHMAD SAIMUN',
            'ISWANDI',
            'HARIZON',
            'JEFRI SAAT PRANATA TAMBA',
            'WANTA ASTRIA',
            'AHMAD DUKI',
            'M. FAJAR ERIN',
            'RAMBI PATTIALA',
            'DEDI SUHENDRI SINAGA',
            'CACA HANDIKA',
            'DHARMA PUTRA PRATAMA',
            'JEVINA LIVIANI',
            'ULI YULIANA',
            'WANDA SYAHPUTRA SIREGAR',
            'WAHYU',
            'ARIF RIDHO',
            'NURHADI',
            'MUHAMMAD ADI SURYA',
            'GUSTI RIYANDI',
            'ALVIANDI SAPUTRA',
            'SUPRIADI',
            'REFLY YANTO',
            'HENKI CANDRA',
            'AYUP PAHRI BUTAR-BUTAR',
            'ELIEZER YOSUA',
            'RIDWAN',
            'FRANSISKUS TIKKOS P SITUMORANG',
            'SOPAN SOFIAN SITANGGANG',
            'ALI SAHRUL MULIADI HASIBUAN',
            'IRVAN ROYNALDY',
            'DWIKA RAJA SYAHPUTRA PURBA',
            'HALIMAH TUSADDIAH DAULAY',
            'KHAIRUL FAHMI',
            'SISWANDO',
            'REFANDO MALAU',
            'RIAN GIBEL SIAHAAN',
            'RULI AKBAR',
            'ARIS MARJOHAN',
            'SALOMO SITUMORANG',
            'TOMI PUTRA SIMARE MARE',
            'MUHAMMAD IKMAL',
            'PATRISIUS CHARLOS SITUMORANG',
            'POLMAN PAULUS SIDABUTAR',
            'JUPRIADI',
            'SETIA ARDINTA',
            'ZULFAHMI',
            'SAS FEGO RIKANDOKA',
            'SYAHRUL EFENDI',
            'VIVI FEBIANTY',
            'YOGI DWI SAPUTRA',
            'RIZKI ARDIAN SINAGA',
            'GABE HAMORAON',
            'HAKIM LUMBANTORUAN',
            'YOGA RYADINATA',
            'WANTO',
            'YOGIE SAPUTRA',
            'TAHI SIANTURI',
            'AFIK VIO PRATAMA',
            'WEWEN SAPUTRA',
            'WIKKI SAMUEL SILITONGA',
            'ALFAJRI',
            'AGUNG ANANDHA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko',
            "KRISDIANTO WIBISONO ",
            "SURYA HANDANI K ",
            "IRWANDA ",
            "PRANS HARDIANSYAH SIMANJUNTAK ",
            "EKA ARDIANSYAH LUBIS ",
            "PANTAS JEKSON LIBERTO TAMPUBOLON ",
        ],
        'SJN' => [],
    ],
    'destoner' => [
        'YBS' => [
            'DONI SAPUTRA',
            'AFRIZA HELMI',
            'RIKI ABDULLAH',
            'RAHID',
            'REGI RINALDI',
            'RAHMADI',
            'ROPIANDI',
            'ERWINDO HASIHOLAN TAMBUNAN',
            'LEONARDO APRIAN PASKALIS SIHOTANG',
            'ARYA GAUTAMA S',
            'INDRA IRANA',
            'MUHAZZIR ALDIAN PANJAITAN',
            'HAIKAL DZIKRI DAMANIK',
            'RIZKI RAMADAN',
            'RISWANDI',
            'LAMA - FERI GUNAWAN',
            'DIMAS PRAYOGA',
            'SOETTA ELOKBUDI ARIN',
            'DENI SAPUTRA',
            'RINALDI',
            'RIKO SAPUTRA DONI',
            'ROMI AFRI YANDI',
            'ALDO PERNANDO',
            'ROMELDI',
            'NANDA SYAHPUTRA SILAEN',
            'MARDIANTO SAPUTRA',
            'APRIANDA TARIGAN',
            'YUDA PRANDIKA HASIBUAN',
            'MUHAMMAD SAFII',
            'AGUM SUNTORO',
            'WIRA CANDRA',
            'MUHAMMAD AL HAFIDZ',
            'MUHAMMAD IHSAN BAJA',
            'BOSMAN SIAHAAN',
            'YOGI SEPDUDEHIYA',
            'PEBRI SETIAWAN',
            'ONY HENDRAWAN',
            'ROBERTO BAGIO',
            'ROMI IRAWAN',
            'WILLIE ATHA RAHMAN',
            'SUPADI CHANDRA',
            'RAMA AGUNG',
            'RINGKI NAPOLA',
            'DENNY SAPITRA',
            'YOGA PANGESTU',
            'HERI SANJAYA',
            'FAUZI JOSHUA TAMPUBOLON',
            'ASRAL',
            'RIZKI REVO',
            'PANDHU BAHARI',
            'DANIEL SITOMPUL',
            'DWIKY ANDRIYAN',
            'IRFAN SHOLEH HARAHAP',
            'SUMADI INDRA ABADI',
            'FITRAH PRABOWO',
            'DALFI ASMANTO',
            'AKHIR ROMADHONA SIREGAR',
            'ARDHY FIRDAUS',
            'RISWAN',
            'ROBI APRIANTO',
            'GUSTIARA HASIBUAN',
            'AFRIZAL',
            'ARIF RAHMAN',
            'ARDIWINATA',
            'MELCHIANUS A.N',
            'MUSHAWWIR AWWAL',
            'BAMBANG NURDIANSYAH',
            'AJIZAN PRAYOGA',
            'CANDRA ANANDA',
            'FAHMI IDRIS',
            'WIRA PRATAMA',
            'FRANSLY SINAMBELA',
            'JANUAR RAMHADAN',
            'RAHMAT AIDIL PUTRA',
            'RAHMAT HIDAYAT',
            'M. RIDWAN',
            'ANDIKA PRATAMA',
            'RIAN IDRIS',
            'ALDI DARMA',
            'ARDI GHAFRANAKA',
            'ARBYE DANIEL SIBURIAN',
            'OLOAN SAHAT MARUBA SIMANJUNTAK',
            'ROYMON EFENDI',
            'FIKRI HIDAYAT',
            'EDON PUTRA',
            'EKI PUTRA',
            'SUGENG MAULANA',
            'TAUFIQ HIDAYAT',
            'HARI ANDRO ROBI MAHYU',
            'ARIF FIDDIN',
            'AZWIN SYAHPUTRA',
            'USMAN NASRULLAH',
            'TINO ANDRIANO',
            'AHMAD SAIMUN',
            'ISWANDI',
            'HARIZON',
            'JEFRI SAAT PRANATA TAMBA',
            'WANTA ASTRIA',
            'AHMAD DUKI',
            'M. FAJAR ERIN',
            'RAMBI PATTIALA',
            'DEDI SUHENDRI SINAGA',
            'CACA HANDIKA',
            'DHARMA PUTRA PRATAMA',
            'JEVINA LIVIANI',
            'ULI YULIANA',
            'WANDA SYAHPUTRA SIREGAR',
            'WAHYU',
            'ARIF RIDHO',
            'NURHADI',
            'MUHAMMAD ADI SURYA',
            'GUSTI RIYANDI',
            'ALVIANDI SAPUTRA',
            'SUPRIADI',
            'REFLY YANTO',
            'HENKI CANDRA',
            'AYUP PAHRI BUTAR-BUTAR',
            'ELIEZER YOSUA',
            'RIDWAN',
            'FRANSISKUS TIKKOS P SITUMORANG',
            'SOPAN SOFIAN SITANGGANG',
            'ALI SAHRUL MULIADI HASIBUAN',
            'IRVAN ROYNALDY',
            'DWIKA RAJA SYAHPUTRA PURBA',
            'HALIMAH TUSADDIAH DAULAY',
            'KHAIRUL FAHMI',
            'SISWANDO',
            'REFANDO MALAU',
            'RIAN GIBEL SIAHAAN',
            'RULI AKBAR',
            'ARIS MARJOHAN',
            'SALOMO SITUMORANG',
            'TOMI PUTRA SIMARE MARE',
            'MUHAMMAD IKMAL',
            'PATRISIUS CHARLOS SITUMORANG',
            'POLMAN PAULUS SIDABUTAR',
            'JUPRIADI',
            'SETIA ARDINTA',
            'ZULFAHMI',
            'SAS FEGO RIKANDOKA',
            'SYAHRUL EFENDI',
            'VIVI FEBIANTY',
            'YOGI DWI SAPUTRA',
            'RIZKI ARDIAN SINAGA',
            'GABE HAMORAON',
            'HAKIM LUMBANTORUAN',
            'YOGA RYADINATA',
            'WANTO',
            'YOGIE SAPUTRA',
            'TAHI SIANTURI',
            'AFIK VIO PRATAMA',
            'WEWEN SAPUTRA',
            'WIKKI SAMUEL SILITONGA',
            'ALFAJRI',
            'AGUNG ANANDHA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko',
            "KRISDIANTO WIBISONO ",
            "SURYA HANDANI K ",
            "IRWANDA ",
            "PRANS HARDIANSYAH SIMANJUNTAK ",
            "EKA ARDIANSYAH LUBIS ",
            "PANTAS JEKSON LIBERTO TAMPUBOLON ",
        ],
        'SJN' => [],
    ],
    'sample_boy' => [
        'YBS' => [
            'Aprianda Tarigan',
            'Andriansyah Lubis',
            'Pengarepen perangin-angin',
            'Wahyu Rizki Maulana',
            'Vega Prayoga',
            'Dodi Irwan Sahputra Butar-butar',
            'Ringki Napola',
            'RAHMAT HIDAYAT',
            'PATRISIUS CHARLOS SITUMORANG',
            'OLOAN S.M. SIMANJUNTAK',
            'ELIZER YOSUA',
            'DENNY SAPITRA',
            'ARYA GAUTAMA S.'
        ],
        'SUN' => [],
        'SJN' => [],
    ],
];
