<x-layouts.app title="Rekap Boiler & Softener">
    <div class="mb-6"><h1 class="text-3xl font-bold text-gray-900">Rekap Boiler &amp; Softener</h1><p class="mt-2 text-sm text-gray-600">Rata-rata nilai parameter per hari.</p></div>
    <x-ui.card>
        <div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
            <form method="GET" action="{{ route('kernel.boiler-softener.rekap') }}" class="flex flex-col sm:flex-row gap-2 sm:gap-4 items-end flex-wrap">
                <div class="flex-1 w-full min-w-[140px]"><label class="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Tanggal Mulai</label><input type="date" name="start_date" value="{{ $startDate }}" class="w-full px-3 py-1.5 sm:px-4 sm:py-2 border border-gray-300 rounded-lg text-sm"></div>
                <div class="flex-1 w-full min-w-[140px]"><label class="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Tanggal Akhir</label><input type="date" name="end_date" value="{{ $endDate }}" class="w-full px-3 py-1.5 sm:px-4 sm:py-2 border border-gray-300 rounded-lg text-sm"></div>
                <div class="flex-1 w-full min-w-[140px]"><label class="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Office/PT</label>@if(auth()->user()->office)<div class="w-full px-3 py-1.5 sm:px-4 sm:py-2 border border-gray-300 rounded-lg text-sm bg-gray-100 text-gray-700">{{ auth()->user()->office }}</div>@else<select name="office" class="w-full px-3 py-1.5 sm:px-4 sm:py-2 border border-gray-300 rounded-lg text-sm"><option value="all" @selected($officeFilter === 'all')>-- Semua Office --</option>@foreach(['YBS', 'SUN', 'SJN'] as $office)<option value="{{ $office }}" @selected($officeFilter === $office)>{{ $office }}</option>@endforeach</select>@endif</div>
                <button type="submit" class="inline-flex items-center justify-center gap-2 px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium transition">Filter</button>
            </form>
            <div class="mt-3 text-sm text-gray-600"><span class="font-medium">Periode:</span><span class="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800">{{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} — {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}</span><span class="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">Office: {{ $officeFilter }}</span></div>
        </div>
        <div class="mt-6">
            @if(empty($dataByDate))
                <div class="text-center py-12"><p class="text-sm text-gray-400">Tidak ada data untuk periode ini.</p></div>
            @else
                <div class="overflow-x-auto border rounded-lg"><table class="min-w-full divide-y divide-gray-200 border border-gray-300 text-xs"><thead><tr><th rowspan="2" class="px-4 py-3 text-left font-bold text-gray-700 uppercase border-r border-b border-gray-300 sticky left-0 bg-indigo-50 z-10">Tanggal</th>@foreach(['boiler' => 'Boiler', 'softener' => 'Softener'] as $jenis => $jenisLabel)<th colspan="{{ count(array_filter($parameterOptions, fn($item) => in_array($jenis, $item['jenis'], true))) }}" class="px-2 py-2 text-center font-bold uppercase border-r border-b border-gray-300 {{ $jenis === 'boiler' ? 'bg-emerald-100 text-emerald-900' : 'bg-sky-100 text-sky-900' }}">{{ $jenisLabel }}</th>@endforeach</tr><tr class="bg-indigo-50">@foreach(['boiler', 'softener'] as $jenis)@foreach($parameterOptions as $parameter => $config)@if(in_array($jenis, $config['jenis'], true))<th class="px-2 py-2 text-center text-[10px] font-semibold text-gray-700 border-r border-b border-gray-300 min-w-[110px]">{{ $config['label'] }} ({{ $config['satuan'] }})</th>@endif @endforeach @endforeach</tr></thead><tbody class="bg-white divide-y divide-gray-200">@foreach($dataByDate as $date => $values)<tr class="hover:bg-gray-50"><td class="px-4 py-3 whitespace-nowrap text-sm font-semibold text-gray-900 border-r border-gray-300 sticky left-0 bg-white z-10">{{ \Carbon\Carbon::parse($date)->format('d/m/Y') }}</td>@foreach(['boiler', 'softener'] as $jenis)@foreach($parameterOptions as $parameter => $config)@if(in_array($jenis, $config['jenis'], true))@php $cell = $values[$jenis . '|' . $parameter] ?? null; @endphp<td class="px-2 py-2 text-center border-r border-gray-300">@if($cell)<span class="font-semibold text-sm text-gray-700">{{ number_format((float) $cell['avg'], 4) }}</span><div class="text-[10px] text-gray-400">{{ $cell['count'] }} data</div>@else<span class="text-gray-300">—</span>@endif</td>@endif @endforeach @endforeach</tr>@endforeach</tbody></table></div>
                <div class="mt-4 text-sm text-gray-600"><span class="font-medium">Total Hari:</span> {{ count($dataByDate) }} hari</div>
            @endif
        </div>
    </x-ui.card>
</x-layouts.app>
